// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHxMdrDh002TQbIJ4wdvY2vIvUWBRtvxM',
    appId: '1:410068067043:web:23238f1507646c636f1bd6',
    messagingSenderId: '410068067043',
    projectId: 'thread-ejseo-2025',
    authDomain: 'thread-ejseo-2025.firebaseapp.com',
    storageBucket: 'thread-ejseo-2025.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_BIZBHeMIRAhF7qKjchYDFsOfReUe0-Q',
    appId: '1:410068067043:android:c2c6de77ba2bfa096f1bd6',
    messagingSenderId: '410068067043',
    projectId: 'thread-ejseo-2025',
    storageBucket: 'thread-ejseo-2025.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDb6QeprcWEOhRhMsqjbLSlSBBS5eK4neY',
    appId: '1:410068067043:ios:5c7e32f4001a914c6f1bd6',
    messagingSenderId: '410068067043',
    projectId: 'thread-ejseo-2025',
    storageBucket: 'thread-ejseo-2025.firebasestorage.app',
    iosBundleId: 'com.example.twitterClone2025',
  );

}